java.lang.NullPointerException: Cannot invoke "pages.generalsetups.CountriesPage.createCountry()" because "this.countriesPage" is null
Fixed this issue and also access to the web elements with varying part of the ID